### ISSUE TITLE
Response From String

### ISSUE THREAD

**Issue by cloud303-cholden** [belak/serde-xmlrpc#20]
I have been running into issues wrapping `response_from_str()` in a generic method. Below is my attempt:

<details>
<summary>Example</summary>

```rust
fn send<'a, U, T>(self, url: U) -> Result<T, CustomError>
where
    U: IntoUrl,
    T: Deserialize<'a>
{
    let body = request_to_string(self.method.as_ref(), self.args)?;
    let resp = reqwest::blocking::Client::new() 
        .post(url)
        .body(body)
        .send()?
        .text()?;
    Ok(response_from_str::<T>(&resp)?)
}
```
</details>

The issue is that this method expects a `&str` argument, but I can't get the argument to outlive the method. Below is the error:

<details>
<summary>Error</summary>

```rust
error[E0597]: `resp` does not live long enough
  --> src/lib.rs:45:35
   |
34 |     fn send<'a, U, T>(self, url: U) -> Result<T, RequestError>
   |             -- lifetime `'a` defined here
...
40 |         let resp = reqwest::blocking::Client::new() 
   |             ---- binding `resp` declared here
...
45 |         Ok(response_from_str::<T>(&resp)?)
   |            -----------------------^^^^^-
   |            |                      |
   |            |                      borrowed value does not live long enough
   |            argument requires that `resp` is borrowed for `'a`
46 |     }
   |     - `resp` dropped here while still borrowed
```
</details>

If I change the signature of `response_from_str()` to accept `String` (see Diff below), it works. Would you be open to a PR to this effect, or is there a better way you recommend going about this? Thanks!

<details>
<summary>Diff</summary>

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 2b7915d..456b09c 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -26,11 +26,11 @@ pub use value::{to_value, Value};
 ///
 /// assert_eq!(val, "hello world".to_string());
 /// ```
-pub fn response_from_str<'a, T>(input: &'a str) -> Result<T>
+pub fn response_from_str<'a, T>(input: String) -> Result<T>
 where
     T: serde::de::Deserialize<'a>,
 {
-    let mut reader = Reader::from_str(input);
+    let mut reader = Reader::from_str(input.as_str());
     reader.expand_empty_elements(true);
     reader.trim_text(true);
 
@@ -460,7 +460,7 @@ mod tests {
                  </struct>
                 </value>
               </fault>
-            </methodResponse>"#,
+            </methodResponse>"#.to_string(),
         )
         .unwrap_err();
 
@@ -487,7 +487,7 @@ mod tests {
               <params>
                 <param><value><string>hello world</string></value></param>
               </params>
-            </methodResponse>"#,
+            </methodResponse>"#.to_string(),
         )
         .unwrap();
```
</details>

**Comment by Carter12s** [comment]
Heyo, I'm looking into this now.

Just to callout what is happening. The trait bound `Deserialize<'a>` says that T is borrowing data from something with lifetime 'a which is why you are having this error. The type `T` that your function is returning depends on data contained in resp, which isn't valid when resp is dropped at the end of the function.

I'd recommend you checkout this page on serde lifetimes: https://serde.rs/lifetimes.html

Essentially, by having the API this way it can be WAY WAY FASTER. But, that doesn't help you with your problem.

Your suggested fix could work, but fundamentally makes the API less efficient. Alternatively, instead of modifying the current implementation of `response_from_str()`, we could make a sister function `response_from_string()` with the API you suggested.

But... give a minute and I'll try to dig into the fix I actually think you want.

**Comment by Carter12s** [comment]
Boom I got it! [Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=40c3b87100961070e1ea76b5200ffc9f)

All you need to do to make your example work is change the trait bound on T in your send function from `Deserialize<'a>` which says "type T is capable of fancy deserialize borrowing in place the memory" to `DeserializeOwned` which says "type T is capable of boring old deserialize that creates new memory". Then everything should work for you.

This is certainly confusing, and someone has to be aware of serde's lifetime relationships to catch on to the fact that DeserializeOwned can be used instead of Deserialize<'a> so maybe we should add response_from_string() anyway? But regardless of whether we do that, you should be un-blocked.

**Comment by belak** [comment]
> Boom I got it! [Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=40c3b87100961070e1ea76b5200ffc9f)

Yep! Good catch! Additionally, you don't need to call `.to_string()` for what you're passing in to `response_from_str` like you did in that example.

I'd rather not add an additional method for this if we don't need to because the existing method can do everything the new one would and more, and potentially faster, with less restrictions on the output types.

Maybe we could add some documentation around `Deserialize<'a>` vs `DeserializeOwned` to make this clearer though?

**Comment by Carter12s** [comment]
Yeah could add an example of specifically this...

**Comment by cloud303-cholden** [comment]
@Carter12s Thanks for taking a swing at this! `DeserializeOwned` is exactly what I need. And thanks for linking the lifetimes article. This makes a lot more sense now. Am I good to close this issue? Or should I leave it open for this documentation action item?

**Comment by Carter12s** [comment]
I'll close this one for now. Hopefully, we get around to some documentation / example improvement, but I don't think we are likely to make a change right away for this issue.
